version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6 

jobs:
  test:
    docker:
      - image: circleci/node:14.15.1
        environment:
          PGHOST: 127.0.0.1
          PG_USERNAME: postgres
          JWT_KEY: just
          NODE_ENV: test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
  
    working_directory: ~/repo

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-

      - run:
          name: install npm packages
          command: npm ci

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json"}}

      - run:
          name: wait for postgres connection
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: unit tests 
          command: npm run test

      - run:
          name: code coverage
          command: npm run coverage

    # - coveralls/upload
      
      - store_artifacts:
          path: ./test-results
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./test-results



workflows:
  build_test:
    jobs:
      - test

